import type { Metadata } from "next";
import { Space_Grotesk, Fira_Code, Sora, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '../contexts/AuthContext'

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-grotesk',
  weight: ['300', '400', '500', '600', '700'], // Add weights you need
});

const firaCode = Fira_Code({
  subsets: ['latin'],
  variable: '--font-code',
  weight: ['400', '500', '600', '700'], // Add weights you need
});

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  weight: ['300', '400', '500', '600', '700'], // Add weights you need
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-n-8" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} ${firaCode.variable} ${sora.variable} antialiased`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
        
      </body>
    </html>
  );
}
